os: linux
dist: focal
group: edge
language: generic
git:
  depth: 1
before_script:
  - cd $HOME && mkdir twrp3
  - mkdir -p ~/.bin
  - PATH="${HOME}/.bin:${PATH}"
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
  - chmod a+rx ~/.bin/repo
  - cd $HOME/twrp3/
  - git config --global user.email "test@gmail.com"
  - git config --global user.name "twrp test"
  - repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
  - travis_wait 30 repo sync -f --force-sync -c --no-clone-bundle --no-tags -j2
script:
  # Replace your ${_USERNAME_}, ${_REPO_SLUG_}, ${_VENDORNAME_}, ${_CODENAME_}
  - cd $HOME/twrp3/ && git clone --branch device-tree https://github.com/TheBeast0403/twrp_device_Nokia_2_2.git device/hmd/WSP_sprout
  - cd $HOME/twrp3/
  - . build/envsetup.sh
  - lunch omni_WSP_sprout-eng
  - cd build
  - chmod a+rx ./envsetup.sh
  - ./envsetup.sh; m -j2 bootimage
  - exit
  - EOF
after_success:
  - echo successfully made boot image!
  - cp $HOME/twrp3/out/target/product/WSP_sprout/boot.img $HOME/twrp3/TWRP-boot.img
  - cd $HOME/twrp3/
  # Optional: You might need to switch from https://transfer.sh to https://file.io
  # - curl -s --upload-file TWRP-$version-WSP_sprout-$(date +"%Y%m%d")-Unofficial.img https://transfer.sh/ && echo ""
deploy:
  provider: releases
  # The secret api_key will be loaded from the environment variables
  token: $GitOAUTHToken
  cleanup: false
  file_glob: true
  file: $HOME/twrp3/TWRP-boot.img
  on:
    tags: false # Set "true" to deploy only on successful tagged commit builds
    repo: TheBeast0403/twrp_device_Nokia_2_2 # Optional: If you want to deploy on different repository
    branch: main # Optional: Needs to be exact as the config branch
branches:
  only:
    - main # Set travis builder branch(es) names
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
