os: linux
dist: focal
group: edge
language: generic
addons:
  apt:
    update:
      - true
    packages:
      - zip
      - tree
services:
  - docker
before_install:
  - docker pull surendrajat/twrp-builder:latest
before_script:
  - cd $HOME && mkdir twrp3
  - mkdir -p ~/.bin
  - PATH="${HOME}/.bin:${PATH}"
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
  - chmod a+rx ~/.bin/repo
  - cd $HOME/twrp3/
  - git config --global user.email "test@gmail.com"
  - git config --global user.name "twrp test"
  - repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
  - travis_wait 30 repo sync -f --force-sync -c --no-clone-bundle --no-tags -j2
script:
  - cd $HOME/twrp3/ && git clone --branch device-tree https://github.com/TheBeast0403/twrp_device_Nokia_2_2.git device/hmd/WSP_sprout
  - rm -rf bootable/recovery && git clone --branch android-11 https://github.com/omnirom/android_bootable_recovery.git bootable/recovery
  - |
    docker run --rm -i -v "$(pwd):/root/twrp3/:rw,z" surendrajat/twrp-builder bash << EOF
    cd /root/twrp3
    source build/envsetup.sh && lunch omni_WSP_sprout-eng && make -j2 bootimage
    exit
    EOF
after_success:
  - curl --upload-file /root/twrp3/out/soong/build.ninja https://transfer.sh/ && echo ""
  - echo successfully made boot image
  - cd $HOME/twrp3/out/target/product/ && tree
  - mkdir $HOME/twrpboot $HOME/tempfiles
  - cp -r $HOME/twrp3/out/target/product/WSP_sprout $HOME/tempfiles
  - cp $HOME/twrp3/out/soong/build.ninja $HOME/tempfiles
  - cd $HOME/twrpboot && zip -r files.zip $HOME/tempfiles
  # Optional: You might need to switch from https://transfer.sh to https://file.io
  - curl --upload-file files.zip https://transfer.sh/ && echo ""
deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GitOAUTHToken
  file_glob: true
  file: $HOME/twrpboot/files.zip
  on:
    tags: false
    repo: TheBeast0403/twrp_device_Nokia_2_2
    branch: master

branches:
  except:
    - /^(?i:untagged)-.*$/
